### ISSUE TITLE
Filtrering av kontaktinfo basert på innbyggers varslingsstatus

### ISSUE THREAD

**Issue by joergenb** [difi/begrep-Oppslagstjenesten#16]
Oppslagstjenesten v5 vil innføre støtte for filtrering av kontaktinfo dersom innbygger ikkje kan varslast ihht eForvaltningsforskriftens §32 andre ledd: 
https://lovdata.no/dokument/SF/forskrift/2004-06-25-988/KAPITTEL_7#§32 

Det innførest eit nytt informasjonsbehov <VarslingsStatus>. 
- Dersom innbygger i førespurnad har oppdaterte kontaktopplysninger, blir desse utlevert saman med varslingsstatus=KAN_VARSLES.
- Dersom innbygger har utløpt kontaktinfo, er reservert, er slettet eller ikke eksisterer i Kontakt- og Reserverasjonsregistere, utleveres ingen kontaktinfo samt varslingsstatus=KAN_IKKE_VARSLES.
- Tjenesten er bakoverkompatibel, så dersom <varslingsstatus> mangler i førespurnad, utleveres alltid kontaktinfo slik som i tidligere versjoner.
- <Varslingsstatus> er kun støttet for HentPersonerFoerespoersel.

**Comment by joergenb** [comment]
closed by #18

**Comment by elsand** [comment]
@joergenb

> er kun støttet for HentPersonerFoerespoersel.

Betyr dette at HentEndringerForespoersel ikke vil inkludere oppføringer der kontaktinfo er blitt eldre enn 18 måneder? 

Kan du si noe om hvordan dette er implementert?

**Comment by joergenb** [comment]
Hei @elsand , ser at formuleringane på denne issuen ikkje stemmer bra med implementasjon.

Det er ingen filtrering i Oppslagstjenesten.  <VarslingsStatus> er ein avleia/berekna verdia basert direkte av datofeltene på personen.  Det skjer ingen endring/hendelse i registeret ved det tidspunktet som datofelta til ein person blir eldre enn 18 månadar.  Det vil difor ikkje bli eit nytt endringsnummer på personen ved utløp av varslbar kontaktinfo.
